version: '3.8'

services:
  code_todo_api:
    image: muratvuranok/todoapp:latest  # Docker Hub'daki image'iniz.
    container_name: Todo_Api
    depends_on:
      - code_todo_db
    environment:
      - ConnectionStrings__DefaultConnection=server=.;database=TodoDb;uid=sa;pwd=Pro247!!;TrustServerCertificate=True;  
    ports:
      - "5001:80"  # Host ve container port eşleşmesi.
    networks:
      - todo-network  # Özel ağa bağlantı.

  code_todo_db:
    image: mcr.microsoft.com/mssql/server:2022-latest  # SQL Server image'i.
    container_name: Todo_Db
    environment:
      SA_PASSWORD: "Pro247!!"  # Veritabanı şifresi.
      ACCEPT_EULA: "Y"  # Lisans anlaşmasını kabul edin.
    ports:
      - "1437:1433"  # SQL Server için port eşleşmesi.
    networks:
      - todo-network  # Özel ağa bağlantı.

networks:
  todo-network:  # Özel ağ tanımı.
    driver: bridge
