name: Docker Hub Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .  
        file: TodoApi/TodoApi/Dockerfile
        push: true
        tags: muratvuranok/todoapp:${{ github.sha }}
        cache-from: type=registry,ref=muratvuranok/todoapp:latest
        cache-to: type=inline

    - name: Docker Image CI
      run: docker run --rm muratvuranok/todoapp:latest  
